### ISSUE TITLE
The setting that you are looking for is not available 

### ISSUE THREAD

**Issue by Shakthi15** [limontec/WhatsApp-GDrive-Downloader#2]
![Screenshot_2020-12-17 App passwords](https://user-images.githubusercontent.com/76106515/102507429-33fbc000-40bf-11eb-9a6a-16a6d1653e32.png)

**Comment by Shakthi15** [comment]
what i get when i Log IN

**Comment by limontec** [comment]
When you get this issue? When click in "Open in Colab"?

**Comment by limontec** [comment]
> what i get when i Log IN

When you get this issue? When click in "Open in Colab"?

**Comment by Shakthi15** [comment]
1st enter the email id 
2nd go to https://myaccount.google.com/apppasswords
3th enter the password and log in and the page like this i try 3 account all the same 
please help to fine the problem .

**Comment by limontec** [comment]
This function is only available if 2FA is enable on your account. 

Troubleshooting:
1- Enable 2FA for your account, https://myaccount.google.com/security .
2- Delete the created Whapa app password and create a new one, https://myaccount.google.com/apppasswords .
3- Not Working? Disable 2FA for your account, https://myaccount.google.com/security .
4- Allow access to your account by unlocking the captchar, https://accounts.google.com/DisplayUnlockCaptcha .
5- Use your password instead of app password you generate.
